Add support for RHEL builds
samba-in-kubernetes/samba-build pull request #49
Opened 2024-07-24 16:07 UTC by anoopcs9

Few considerations from the approach used here:
- In order to satisfy the dependency for _libthrift_ from ceph we restrictively enable EPEL during build and installation testing process.
- For registration purposes we have the following environment variables:
  - `ORG_ID` : ID to register with one of multiple organizations
  - `ACT_KEY`: activation key to use for registration

fixes #47

2024-07-25 09:43 UTC, obnoxxx requested changes
This is a great step toward adding rhel builds.

Apart from the detail request about the invocation of subscription-manger, I have these requests:


* I get an error that subscription-manager should be run on the host and not in the container.
* could you add instructions for building RHEL rpms to the readme?
*

2024-07-25 09:43 UTC, obnoxxx commented on ansible/roles/build.rpms.rhel/files/rpm-build.sh
> +subscription-manager register --org "${ORG_ID}" --activationkey "${ACT_KEY}"
```suggestion
subscription-manager register --org="${ORG_ID}" --activationkey="${ACT_KEY}"
```

I believe these options need an `=` symbol. and doesn't subscription-manager beed to run under sudo or directly as root?

2024-07-25 16:29 UTC, obnoxxx commented on ansible/roles/build.rpms.rhel/files/rpm-build.sh
> +subscription-manager register --org "${ORG_ID}" --activationkey "${ACT_KEY}"
forget the comment about sudo: the commands are running as root in the container anyways.

2024-07-25 16:31 UTC, obnoxxx requested changes
Now it worked for me locally! 

It was important to **not** have the host system registered.

I still request to add instructions to the docs/readme.

2024-07-25 20:59 UTC, andrewschoen commented
Thanks for doing this work! I've been testing downstream and am seeing the following issue with `podman`. I've had some issues before using `podman` in this environment for builds before as well.

This looks like https://bugzilla.redhat.com/show_bug.cgi?id=1998835 - I've tried the workarounds mentioned in the BZ with no luck so far. podman version is `podman-4:4.9.4-4.module+el8.10.0+21995+81e8507c.x86_64 `

```
TASK [build.rpms.rhel : Build rhel 9 rpms in a container] **********************
task path: /workspace/app/one-pipeline-config-repo/samba-build/ansible/roles/build.rpms.rhel/tasks/main.yml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1721940471.2924242-2605-197220266570013 `" && echo ansible-tmp-1721940471.2924242-2605-197220266570013="` echo /root/.ansible/tmp/ansible-tmp-1721940471.2924242-2605-197220266570013 `" ) && sleep 0'
Using module file /workspace/app/one-pipeline-config-repo/samba-build/venv/lib64/python3.11/site-packages/ansible_collections/containers/podman/plugins/modules/podman_container.py
<localhost> PUT /root/.ansible/tmp/ansible-local-15365hp1srid/tmpdcou6shq TO /root/.ansible/tmp/ansible-tmp-1721940471.2924242-2605-197220266570013/AnsiballZ_podman_container.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1721940471.2924242-2605-197220266570013/ /root/.ansible/tmp/ansible-tmp-1721940471.2924242-2605-197220266570013/AnsiballZ_podman_container.py && sleep 0'
<localhost> EXEC /bin/sh -c '/workspace/app/one-pipeline-config-repo/samba-build/venv/bin/python3.11 /root/.ansible/tmp/ansible-tmp-1721940471.2924242-2605-197220266570013/AnsiballZ_podman_container.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1721940471.2924242-2605-197220266570013/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "arch": null,
            "attach": null,
            "authfile": null,
            "blkio_weight": null,
            "blkio_weight_device": null,
            "cap_add": null,
            "cap_drop": null,
            "cgroup_conf": null,
            "cgroup_parent": null,
            "cgroupns": null,
            "cgroups": null,
            "chrootdirs": null,
            "cidfile": null,
            "cmd_args": null,
            "command": "/tmp/files/rpm-build.sh",
            "conmon_pidfile": null,
            "cpu_period": null,
            "cpu_quota": null,
            "cpu_rt_period": null,
            "cpu_rt_runtime": null,
            "cpu_shares": null,
            "cpus": null,
            "cpuset_cpus": null,
            "cpuset_mems": null,
            "debug": false,
            "decryption_key": null,
            "delete_depend": null,
            "delete_time": null,
            "delete_volumes": null,
            "detach": false,
            "detach_keys": null,
            "device": null,
            "device_cgroup_rule": null,
            "device_read_bps": null,
            "device_read_iops": null,
            "device_write_bps": null,
            "device_write_iops": null,
            "dns": null,
            "dns_option": null,
            "dns_search": null,
            "entrypoint": null,
            "env": {
                "ACT_KEY": "****",
                "MOCK_DIR": "/tmp/samba-build/mock",
                "ORG_ID": "****",
                "OS_VERS": "9",
                "RPMS_DIR": "/tmp/samba-build/rpms",
                "SAMBA_SRPM": "samba-4.20.3.20240723.085624.4cf9af9186d-1.el8.src.rpm",
                "SAMBA_VERS": "4.20",
                "SRPM_DIR": "/tmp/samba-build/srpms"
            },
            "env_file": null,
            "env_host": null,
            "env_merge": null,
            "etc_hosts": null,
            "executable": "podman",
            "expose": null,
            "force_delete": true,
            "force_restart": false,
            "generate_systemd": {},
            "gidmap": null,
            "gpus": null,
            "group_add": null,
            "group_entry": null,
            "health_startup_cmd": null,
            "health_startup_interval": null,
            "health_startup_retries": null,
            "health_startup_success": null,
            "health_startup_timeout": null,
            "healthcheck": null,
            "healthcheck_failure_action": null,
            "healthcheck_interval": null,
            "healthcheck_retries": null,
            "healthcheck_start_period": null,
            "healthcheck_timeout": null,
            "hooks_dir": null,
            "hostname": null,
            "hostuser": null,
            "http_proxy": null,
            "image": "[registry.access.redhat.com/ubi9](http://registry.access.redhat.com/ubi9)",
            "image_strict": false,
            "image_volume": null,
            "init": null,
            "init_ctr": null,
            "init_path": null,
            "interactive": null,
            "ip": null,
            "ip6": null,
            "ipc": null,
            "kernel_memory": null,
            "label": null,
            "label_file": null,
            "log_driver": null,
            "log_level": null,
            "log_opt": null,
            "mac_address": null,
            "memory": null,
            "memory_reservation": null,
            "memory_swap": null,
            "memory_swappiness": null,
            "mount": null,
            "name": "rhel_samba_build",
            "network": null,
            "network_aliases": null,
            "no_healthcheck": null,
            "no_hosts": null,
            "oom_kill_disable": null,
            "oom_score_adj": null,
            "os": null,
            "passwd": null,
            "passwd_entry": null,
            "personality": null,
            "pid": null,
            "pid_file": null,
            "pids_limit": null,
            "platform": null,
            "pod": null,
            "pod_id_file": null,
            "preserve_fd": null,
            "preserve_fds": null,
            "privileged": true,
            "publish": null,
            "publish_all": null,
            "pull": null,
            "quadlet_dir": null,
            "quadlet_filename": null,
            "quadlet_options": null,
            "rdt_class": null,
            "read_only": null,
            "read_only_tmpfs": null,
            "recreate": false,
            "requires": null,
            "restart_policy": null,
            "restart_time": null,
            "retry": null,
            "retry_delay": null,
            "rm": true,
            "rmi": null,
            "rootfs": null,
            "sdnotify": null,
            "seccomp_policy": null,
            "secrets": null,
            "security_opt": null,
            "shm_size": null,
            "shm_size_systemd": null,
            "sig_proxy": null,
            "state": "started",
            "stop_signal": null,
            "stop_time": null,
            "stop_timeout": null,
            "subgidname": null,
            "subuidname": null,
            "sysctl": null,
            "systemd": null,
            "timeout": null,
            "timezone": null,
            "tls_verify": null,
            "tmpfs": null,
            "tty": null,
            "uidmap": null,
            "ulimit": null,
            "umask": null,
            "unsetenv": null,
            "unsetenv_all": null,
            "user": null,
            "userns": null,
            "uts": null,
            "variant": null,
            "volume": [
                "/workspace/app/one-pipeline-config-repo/samba-build/ansible/roles/build.rpms.rhel/files:/tmp/files:z",
                "/tmp/samba-build:/tmp/samba-build:z"
            ],
            "volumes_from": null,
            "workdir": null
        }
    },
  [...]

2024-07-26 06:18 UTC, anoopcs9 commented
> Thanks for doing this work! I've been testing downstream and am seeing the following issue with `podman`. I've had some issues before using `podman` in this environment for builds. We were told in that instance to use `docker` instead of `podman` for container builds.
> 
> This looks like https://bugzilla.redhat.com/show_bug.cgi?id=1998835 - I've tried the workarounds mentioned in the BZ with no luck so far. podman version is `podman-4:4.9.4-4.module+el8.10.0+21995+81e8507c.x86_64 `

Thanks for trying out the patch.

In order to mitigate any possible issues with `podman` on RHEL machines I have updated the patch to allow building the rpms locally on a **registered** host. See relevant section from updated PR [description](https://github.com/samba-in-kubernetes/samba-build/pull/49#issue-2427976024).

2024-07-26 12:04 UTC, obnoxxx commented
@anoopcs9  wrote: 

> Thanks for trying out the patch.
> 
> In order to mitigate any possible issues with `podman` on RHEL machines I have updated the patch to allow building the rpms locally on a **registered** host.

I tested this and was able to build rhel rpms locally on a registered fedora host.


but the first attempts failed with a message from mock that the password I entered was wrong.
But I did not enter any password and there was no prompt.
It started building after I had added my local user to the mock group.


Testing the rpm install via `make test.rpms.rhel` still works through podman though, and in order to do it, I had to take a few steps:

* `ubscription-manager unregister`
*  invoke `make rpms.rhel`with the ÒRG_ID`and `ACT_KEY` vars set.

After that, the installation of the locally built packages worked just fine!






> See relevant section from updated PR [description](https://github.com/samba-in-kubernetes/samba-build/pull/49#issue-2427976024).


I think with a corresponding addition to the readme we can soon get this merged.

Alternatively, this can also be done as a follow-up.

2024-07-26 13:51 UTC, andrewschoen commented
> Thanks for trying out the patch.
> 
> In order to mitigate any possible issues with `podman` on RHEL machines I have updated the patch to allow building the rpms locally on a **registered** host. See relevant section from updated PR [description](https://github.com/samba-in-kubernetes/samba-build/pull/49#issue-2427976024).

I've run another test with this latest update and see a different issue. I've seen this before when running `mock` in this environment. I think our issue here is running `podman` in a "Docker in Docker" sidecar in kubernetes. I'd really like to understand better the issue of running `podman` in this environment and I haven't been able to get there yet. I'm going to try again by running this playbook through a centos:stream9 container started on the sidecar with `docker run --priviliged ..`. This was how I was able to get around the following in previous builds:

```
TASK [build.rpms.rhel : Build rhel 9 rpms locally] *****************************
task path: /workspace/app/one-pipeline-config-repo/samba-build/ansible/roles/build.rpms.rhel/tasks/main.yml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1722001146.0461717-2584-78415589841125 `" && echo ansible-tmp-1722001146.0461717-2584-78415589841125="` echo /root/.ansible/tmp/ansible-tmp-1722001146.0461717-2584-78415589841125 `" ) && sleep 0'
Using module file /workspace/app/one-pipeline-config-repo/samba-build/venv/lib64/python3.11/site-packages/ansible/modules/command.py
<localhost> PUT /root/.ansible/tmp/ansible-local-15157fuujmxc/tmp8goccgkm TO /root/.ansible/tmp/ansible-tmp-1722001146.0461717-2584-78415589841125/AnsiballZ_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1722001146.0461717-2584-78415589841125/ /root/.ansible/tmp/ansible-tmp-1722001146.0461717-2584-78415589841125/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/workspace/app/one-pipeline-config-repo/samba-build/venv/bin/python3.11 /root/.ansible/tmp/ansible-tmp-1722001146.0461717-2584-78415589841125/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1722001146.0461717-2584-78415589841125/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": [
        "/usr/bin/mock",
        "--root",
        "/tmp/samba-build/mock/rhel-9-x86_64.cfg",
        "--resultdir",
        "/tmp/samba-build/rpms/4.20/rhel/9/x86_64",
        "--rebuild",
        "/tmp/samba-build/srpms/samba-4.20.3.20240723.085624.4cf9af9186d-1.el8.src.rpm"
    ],
    "delta": "0:00:00.978119",
    "end": "2024-07-26 13:39:07.326946",
    "invocation": {
        "module_args": {
            "_raw_params": "/usr/bin/mock --root /tmp/samba-build/mock/rhel-9-x86_64.cfg --resultdir /tmp/samba-build/rpms/4.20/rhel/9/x86_64 --rebuild /tmp/samba-build/srpms/samba-4.20.3.20240723.085624.4cf9af9186d-1.el8.src.rpm",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "expand_argument_vars": true,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true
        }
    },
    "msg": "non-zero return code",
    "rc": 80,
    "start": "2024-07-26 13:39:06.348827",
    "stderr": "INFO: [mock.py](http://mock.py/) version 5.6 starting (python version = 3.6.8, NVR = mock-5.6-1.el8), args: /usr/libexec/mock/mock --root /tmp/samba-build/mock/rhel-9-x86_64.cfg --resultdir /tmp/samba-build/rpms/4.20/rhel/9/x86_64 --rebuild /tmp/samba-build/srpms/samba-4.20.3.20240723.085624.4cf9af9186d-1.el8.src.rpm\nStart(bootstrap): init plugins\nINFO: selinux disabled\nFinish(bootstrap): init plugins\nStart: init plugins\nINFO: selinux disabled\nFinish: init plugins\nINFO: Signal handler active\nStart: run\nERROR: Namespace unshare failed.\nINFO: Guessed host environment type: unknown",
    "stderr_lines": [
        "INFO: [mock.py](http://mock.py/) version 5.6 starting (python version = 3.6.8, NVR = mock-5.6-1.el8), args: /usr/libexec/mock/mock --root /tmp/samba-build/mock/rhel-9-x86_64.cfg --resultdir /tmp/samba-build/rpms/4.20/rhel/9/x86_64 --rebuild /tmp/samba-build/srpms/samba-4.20.3.20240723.085624.4cf9af9186d-1.el8.src.rpm",
        "Start(bootstrap): init plugins",
        "INFO: selinux disabled",
        "Finish(bootstrap): init plugins",
        "Start: init plugins",
        "INFO: selinux disabled",
        "Finish: init plugins",
        "INFO: Signal handler active",
        "Start: run",
        "ERROR: Namespace unshare failed.",
        "INFO: Guessed host environment type: unknown"
    ],
    "stdout": "",
    "stdout_lines": []
``` 

See this issue for more context: https://github.ibm.com/ceph/ibm-tools/issues/568

2024-07-26 19:37 UTC, andrewschoen commented
I've been doing some more testing and can get a centos 9 build downstream with this PR. Still working on the rhel 9 build, I don't think the issues I'm having are related to this PR though. Thanks again for your work here!

If curious, these are the scripts I'm using to build downstream. https://github.ibm.com/ceph/ceph-pipeline-configs/pull/6

2024-07-27 18:11 UTC, anoopcs9 commented
> > Thanks for trying out the patch.
> > In order to mitigate any possible issues with `podman` on RHEL machines I have updated the patch to allow building the rpms locally on a **registered** host. See relevant section from updated PR [description](https://github.com/samba-in-kubernetes/samba-build/pull/49#issue-2427976024).
> 
> I've run another test with this latest update and see a different issue. I've seen this before when running `mock` in this environment. I think our issue here is running `podman` in a "Docker in Docker" sidecar in kubernetes.

The latest version of the change doesn't require `podman` at all. Or is it like your host itself is a registered `podman` container?  If so the
> ERROR: Namespace unshare failed.

error should not be seen with a container host running in privileged(`--privileged`) mode.

2024-07-29 09:12 UTC, obnoxxx commented
> > > Thanks for trying out the patch.
> > > In order to mitigate any possible issues with `podman` on RHEL machines I have updated the patch to allow building the rpms locally on a **registered** host. See relevant section from updated PR [description](https://github.com/samba-in-kubernetes/samba-build/pull/49#issue-2427976024).
> > 
> > 
> > I've run another test with this latest update and see a different issue. I've seen this before when running `mock` in this environment. I think our issue here is running `podman` in a "Docker in Docker" sidecar in kubernetes.
> 


@anoopcs9  wrote:
> The latest version of the change doesn't require `podman` at all.

Well there is at least an explicit  dependency on podman when using the buil-in-container mode:

https://github.com/samba-in-kubernetes/samba-build/pull/49/files#diff-eef9e2db91ee0cb9e8e7bfd9f8ff30e562bc192241cf1f8a8cc6ef02ea9f33dd 

it seems like being able to use docker instead of podman  in this mode might already help @andrewschoen .

2024-07-29 10:05 UTC, obnoxxx reviewed
I am tempted to approve and merge this PR as is since both modes (container-build and local build are working for me on my Fedora host. 

I think we can update the Readme as a follow-up.

Likewise, I think we should be able to solve the podman problems that @andrewschoen  is facing independently once this is in.

2024-07-29 13:20 UTC, anoopcs9 commented
> I am tempted to approve and merge this PR as is since both modes (container-build and local build are working for me on my Fedora host.

Please wait..I'm improvising a little more in the direction of reusable script for both cases.

2024-07-29 15:01 UTC, andrewschoen commented
> I am tempted to approve and merge this PR as is since both modes (container-build and local build are working for me on my Fedora host.
> 
> I think we can update the Readme as a follow-up.
> 
> Likewise, I think we should be able to solve the podman problems that @andrewschoen is facing independently once this is in.

I agree here. I am stuck with using `docker` right now and am working to address this issue because not being able to use `podman` longterm is going to be very limiting.

The latest changes were enough to help me out, while still using `docker`. I'd hestiate to invest too much work into `docker` support though because I'm not sure it's very helpful to anybody else outside of my current situation.

2024-07-30 11:08 UTC, anoopcs9 commented
> > I am tempted to approve and merge this PR as is since both modes (container-build and local build are working for me on my Fedora host.
> 
> Please wait..I'm improvising a little more in the direction of reusable script for both cases.

I take back my request. I ended up with lot more changes than I expected. May be I'll come back at some other time but for now I've updated with an extra README section to explain the situation with RHEL builds.

2024-07-30 16:52 UTC, obnoxxx approved these changes
This is working nicely for me now.

Thanks for updating the Readme!

The readme will need some additional tweaks for registration, but those can be added after the fact.

LGTM

2024-07-30 16:52 UTC, merged